#!/usr/bin/env python3


import subprocess


def main():
    tty = subprocess.check_output(['/usr/local/bin/tmux', 'display', '-p', '#{pane_tty}'])
    tty = str(tty, encoding='utf-8').strip('\n')
    sshpara = subprocess.check_output(['/bin/ps', '-t', tty, '-o', 'command'])
    sshpara = str(sshpara, encoding='utf-8').split('\n')
    for i in sshpara:
        if 'ssh' in i:
            # raise SystemExit
            sshcmd = str(i)
            # __import__('ipdb').set_trace()
            rminfotmp = subprocess.check_output("{0} 'PYTHONIOENCODING=utf-8 python3' < '/Users/shingo/gitrepo/Mytmuxconf/tmux-mclnr'".format(sshcmd), shell=True)
            rminfo = str(rminfotmp, encoding='utf-8').strip('\n')
            # return ("{0}".format(rminfo))
            print(rminfo)
            # raise SystemExit
    # os.popen('python3 ./tmux-mclnr')
    # subprocess.check_output(['python3', './tmux-mclnr'])


mclnrinfo = subprocess.check_output(['/usr/local/bin/python3', '/Users/shingo/gitrepo/Mytmuxconf/tmux-mclnr'])
mclnrinfo = str(mclnrinfo, encoding='utf-8').strip('\n')
# return ("{0}".format(mclnrinfo))
print(mclnrinfo)


if __name__ == "__main__":
    main()
