#!/usr/bin/env python3


import re
import os
import sys
import subprocess
import psutil

sco = subprocess.check_output
curpath = os.path.dirname(os.path.realpath(__file__))
payloadpath = curpath + "/tmux-monitor"
# tty = "ttys012"
tty = sco(['tmux', 'display', '-p', '#{pane_tty}'])
tty = str(tty, encoding='utf-8').strip('\n')
sshpara = sco(['/bin/ps', '-t', tty, '-o', 'command'])
sshpara = str(sshpara, encoding='utf-8').split('\n')
sshcmd = [str(i) for i in sshpara if 'ssh ' in i]
sshcmd = sshcmd[0] if len(sshcmd) != 0 else None

if os.uname()[0] == 'Darwin':
    nictype = 'en0'
else:
    nictype = 'eth0'


def colouroutput(u, h, **m):
    # pass
    colourprefix = ('fg=', 'bg=')
    f, b = colourprefix
    uhcolourdef = ('magenta', 'default', 'colour148', 'colour24')
    fger, bger, fgd, bgd = uhcolourdef
    uhd = dict(un=u, ha=h, fgerr=f + fger, bgerr=b + bger, fgdt=f + fgd, bgdt=b + bgd)
    if u == "root":
        print("#[{fgerr},{bgerr}]{un}#[{fgdt},{bgdt}]@{ha}".format(**uhd))
    elif u is None and h is None:
        pass
    else:
        print("#[{fgdt},{bgdt}]{un}#[{fgdt},{bgdt}]@{ha}".format(**uhd))

    if len(m) != 0:
        m = [i for i in m.values()]
        m = m[0]
        mc = re.split(r'(?<=])(\s+)', m)[0]
        mcsl = re.split('(\s|])', mc)
        cup = float(re.split('(\s|])', mc)[2].strip('%'))
        # mccup = re.search('(?<=\s)[\d+.\d+]+(?=%)', mc)
        net = re.split(r'(?<=])(\s+)', m)[2]
        disk = re.split(r'(?<=])(\s+)', m)[-1]
        dinfl = re.split(r'(:|\s)+', disk)
        # ['D', ':', '[/', ':', '41.2%', ' ', 'W↓', ':', '0.0KB/s]']
        rpup = float(re.split(r'(:|\s)+', disk)[4].strip('%'))
        dinf1 = ''.join(dinfl[0:4])
        dinf2 = dinfl[4]
        dinf3 = ''.join(dinfl[5:9])
        monitorcoldef = ('colour24', 'black', 'white',
                         'yellow,bright', 'magenta', 'default')
        fgmc, fgnet, fgdrv, cbgc, cfgerr, cdebg = monitorcoldef
        mond = dict(mcs=mc, nis=net, dis=disk, cdebgc=b + cdebg, cerrfg=f + cfgerr,
                    mci1=mcsl[0], mci2=mcsl[2], mci3=mcsl[-2], mcfg=f + fgmc,
                    netfg=f + fgnet, drvfg=f + fgdrv, cbyb=b + cbgc,
                    di1=dinf1, di2=dinf2, di3=dinf3)
        if cup > 85.0:
            mcis = "#[{mcfg},{cbyb}]{mci1} #[{cerrfg},{cdebgc}]{mci2}#[{mcfg},{cbyb}]{mci3}".format(**mond)
        else:
            mcis = "#[{mcfg},{cbyb}]{mcs}".format(**mond)
        # -------------------------------------------------------
        nets = "#[{netfg},{cbyb}]{nis}".format(**mond)
        # -------------------------------------------------------
        if rpup > 80.0:
            drvs = "#[{mcfg},{cbyb}]{di1} #[{cerrfg},{cdebgc}]{di2}#[{mcfg},{cbyb}]{di3}".format(**mond)
        else:
            drvs = "#[{drvfg},{cbyb}]{dis}".format(**mond)

        print("{0} {1} {2}".format(mcis, nets, drvs))


def get_remac_info(lrlocation):
    pyenv = "PYTHONIOENCODING=utf-8 python3"
    pyenvc = r"'PYTHONIOENCODING=utf-8 python3 -c"
    getuserpara = r'"import os;print(os.getlogin())"\\\''
    rsshusern = sco('{0} {1} {2}'.format(
        sshcmd, pyenvc, getuserpara), shell=True)
    rsshusern = str(rsshusern, encoding='utf-8').strip('\n')
    # sco('ssh aecs \'PYTHONIOENCODING=utf-8 python3 -c "import os;print(os.getlogin())"\'', shell=True)

# sshipaddr = sco('ssh aecs \'PYTHONIOENCODING=utf-8 python3 -c "import psutil;print(psutil.net_if_addrs()[\\"eth0\\"][0][1])"\'', shell=True)
    # getipadpara = r'"import psutil;print(psutil.net_if_addrs())"\\\''
    # __import__('ipdb').set_trace()
    getipadpara = r'"import psutil;print(psutil.net_if_addrs()[\"eth0\"][0][1])"\\\''
    reminsiip = sco('{0} {1} {2}'.format(
        sshcmd, pyenvc, getipadpara), shell=True)
    reminsiip = str(reminsiip, encoding='utf-8').strip('\n')
    if lrlocation == "left":
        colouroutput(rsshusern, reminsiip)
        # print("{0}@{1}".format(rsshusern, reminsiip))
    else:
        rminfotmp = sco("{0} '{1}' < '{2}'".format(
            sshcmd, pyenv, payloadpath), shell=True)
        rminfo = str(rminfotmp, encoding='utf-8').strip('\n')
        # print(rminfo)
        colouroutput(None, None, m=rminfo)


def main():
    sys.argv.append("")
    slorsr = sys.argv[1]

    if sshcmd is None:
        if slorsr == "left":
            username = os.getlogin()
            hostaddr = psutil.net_if_addrs()[nictype][0][1]
            colouroutput(username, hostaddr)
            # if username == "shingo":
            #     print("#[fg=red,bg=colour24]{0}#[fg=colour148,bg=colour24]@{1}".format(username, hostaddr))
            # print("{0}@{1}".format(username, hostaddr))
        else:
            mclnrinfo = subprocess.check_output(
                "python3 {0}".format(payloadpath), shell=True)
            mclnrinfo = str(mclnrinfo, encoding='utf-8').strip('\n')
            # print(mclnrinfo)
            colouroutput(None, None, m=mclnrinfo)
    else:
        get_remac_info(slorsr)


if __name__ == "__main__":
    main()
